site_name: 个人笔记
nav:
  - 主页: index.md
  - 软件开发:
    - 多线程编程:
      - Pthreads多线程编程: pthreads_multithreading.md
      - C++多线程编程: cpp_multithreading.md

  - 计算机视觉:
    - 视频技术: 
        - 视频编解码: video_codec.md
    # - OpenCV: computer_vision.md

  - 环境搭建:
    - 交叉编译OpenSSH: cross_compile_openssh.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tabbed
  - footnotes
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.arithmatex:
      generic: true
  - meta

theme:
  name: material
  palette:
    primary: indigo
  language: zh

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://cdn.plot.ly/plotly-latest.min.js